DISTRIBUTED_CONFIG_FIELD = "__kedroazureml_distributed_config__"
PARAMS_PREFIX = "params:"

# MLflow integration env vars (set by generator, read by MlflowAzureMLHook)
KEDRO_AZUREML_MLFLOW_ENABLED = "KEDRO_AZUREML_MLFLOW_ENABLED"
KEDRO_AZUREML_MLFLOW_RUN_NAME = "KEDRO_AZUREML_MLFLOW_RUN_NAME"
KEDRO_AZUREML_MLFLOW_EXPERIMENT_NAME = "KEDRO_AZUREML_MLFLOW_EXPERIMENT_NAME"
KEDRO_AZUREML_MLFLOW_NODE_NAME = "KEDRO_AZUREML_MLFLOW_NODE_NAME"
